### ISSUE TITLE
Give appropriate http status

### ISSUE THREAD

**Issue by ximanta** [stackroute/boeing-wave3-pie#11]
insurerregservice/src/main/java/com/stackroute/pie/controller/InsurerController.java

**Comment by abhishekbanka1313** [comment]
Gave appropriate http status in insurerregservice/src/main/java/com/stackroute/pie/controller/InsurerController.java

**Comment by RakhshandaNoor** [comment]
Not done completely
appropriate http status in insurerregservice/src/main/java/com/stackroute/pie/controller/InsurerController.java

**Comment by abhishekbanka1313** [comment]
Updated the controller of Insurer
