### ISSUE TITLE
incorrect parent  and missing indentation

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/boeing-wave3-pie#12]
boeing-wave3-pie/searchservice/pom.xml
<parent>
		<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.2.RELEASE</version>
	<relativePath/>  
	</parent>

**Comment by sourabhimurthy** [comment]
Resolved issues
