### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by ximanta** [stackroute/boeing-wave3-pie#9]
insurerregservice/src/main/java/com/stackroute/pie/services/InsurerDetailsServiceImpl.java

//        Insurer insurer1 = insurerRepository.findByInsurerLicense(insurerLicense).get();
//        System.out.println("Insurer data is "+insurer1.toString());
        // Policy policy1 = insurerRepository.findByPoliciesPolicyId(policyId);
//        System.out.println("Policy Id:"+policy1.getPolicyId());
//        System.out.println("policy1 is "+policy1);
//        return policy1;
//
//  insurerRepository.deleteByPoliciesPolicyId(policyId);

**Comment by abhishekbanka1313** [comment]
Removed the commented code in the insurerregservice/src/main/java/com/stackroute/pie/services/InsurerServiceImpl.java
